############################################################
# BITHub - data directory
# Use this to change locations to directories of data
#############################################################


bulk:
  raw:
    brainseq: "/home/neuro/Documents/BrainData/Bulk/Brainseq"
    brainspan: "/home/neuro/Documents/BrainData/Bulk/BrainSpan/Kang/genes_matrix_csv"
    gtex: "/home/neuro/Documents/BrainData/Bulk/GTEx"
    hdbr: "/home/neuro/Documents/BrainData/Bulk/HDBR" # Downloaded from recount data but some files exist
    psychencode: "/home/neuro/Documents/BrainData/Bulk/PsychEncode"

  formatted:
    brainseq:
      dir: "/home/neuro/Documents/Brain_integrative_transcriptome/update/bithub/data-preprocessing/output"
      expr: "expression/BrainSeq-exp.csv"
      metadata: "metadata/BrainSeq-metadata.csv"
      rownames: 1
    brainspan:
      dir: "/home/neuro/Documents/Brain_integrative_transcriptome/update/bithub/data-preprocessing/output"
      expr: "expression/BrainSpan-exp.csv"
      metadata: "metadata/BrainSpan-metadata.csv"
      rownames: 1
    gtex:
      dir: "/home/neuro/Documents/Brain_integrative_transcriptome/update/bithub/data-preprocessing/output"
      expr: "expression/GTEx-exp.csv"
      metadata: "metadata/GTEx-metadata.csv"
      rownames: 1
    psychencode:
      dir: "/home/neuro/Documents/Brain_integrative_transcriptome/update/bithub/data-preprocessing/output"
      expr: "expression/PsychEncode-exp.csv"
      metadata: "metadata/PsychEncode-metadata.csv"
      rownames: 1
    hdbr:
      dir: "/home/neuro/Documents/Brain_integrative_transcriptome/update/bithub/data-preprocessing/output"
      expr: "expression/HDBR-exp.csv"
      metadata: "metadata/HDBR-metadata.csv"
      drop_cols: ["X"]
      rownames: "EnsemblID"


single_nucleus:
  raw:
    hca: "/home/neuro/Documents/BrainData/single-cell/hca/Raw"
    cameron: "/home/neuro/Documents/BrainData/single-cell/cameron"
    velmeshev: "/home/neuro/Documents/BrainData/single-cell/velmeshev/2026-data"

  formatted:
    hca:
      dir: "/home/neuro/Documents/Brain_integrative_transcriptome/update/bithub/data-preprocessing/output"
      expr: "expression/HCA-exp.csv"
      metadata: "metadata/HCA-metadata.csv"
    cameron:
      dir: "/home/neuro/Documents/Brain_integrative_transcriptome/update/bithub/data-preprocessing/output"
      expr: "expression/Cameron-exp.csv"
      metadata: "metadata/Cameron-metadata.csv"

    velmeshev:
      dir: "/home/neuro/Documents/Brain_integrative_transcriptome/update/bithub/data-preprocessing/output"
      expr: "expression/Velmeshev-exp.csv"
      metadata: "metadata/Velmeshev-metadata.csv"
