# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndata.proto\"\x19\n\x07RowData\x12\x0e\n\x06values\x18\x01 \x03(\x02\"8\n\tTableData\x12\x14\n\x0c\x66loat_values\x18\x01 \x03(\x02\x12\x15\n\rstring_values\x18\x02 \x03(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ROWDATA._serialized_start=14
  _ROWDATA._serialized_end=39
  _TABLEDATA._serialized_start=41
  _TABLEDATA._serialized_end=97
# @@protoc_insertion_point(module_scope)
