name: bithub-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python<3.12
  - terraform
  - awscli
  - protobuf
  - uutils-coreutils
  - pip
  - pip:
    - oyaml
    - h5py
    - tqdm
    - boto3
    - numpy
    - scipy